export const USER = 'USER'
export const TOKEN = 'TOKEN'
export const CLEAR_USER = 'CLEAR_USER'
export const ALLPOSTS = 'ALLPOSTS'
export const MYPOSTS = 'MYPOSTS'
export const POST_ERROR = 'POST_ERROR'
export const SET_LOADING = 'SET_LOADING'
export const REMOVE_LOADING = 'REMOVE_LOADING'
